<?php

/**
 * Implements of hook_webform_component_info().
 */
function webform_simplenews_webform_component_info() {
  $components = array();
  $components['newsletter_email'] = array(
    'label' => t('Newsletter email'),
    'description' => t('Email for newsletter'),
    'features' => array(
      'csv' => TRUE,
      'email' => TRUE,
      'required' => TRUE,
      'conditional' => TRUE,
      'email_address' => TRUE,
      'spam_analysis' => TRUE,
    ),
    'file' => 'webform_simplenews.inc',
  );
  return $components;
}