<?php

/**
 * @file
 * Prints PHP code
 *
 * Lets a User see the output of his PHP code to develope
 * their PHP skills
 */
  
  
/**
 * Implementation of hook_menu()
 */
function annotate_menu() {
  $items['admin/config/annotate'] = array(
    'title' => 'Annotate Module',
    'description' => 'Adjust Annotate settings.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system')
  );
  
  $items['admin/config/annotate/settings'] = array(
    'title' => 'Annotate Settings',
    'description' => 'Toggle Annotate functionality.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('annotate_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'annotate.admin.inc'
  );
  
  return $items;
}
